#include <iostream>
#include <memory>
#include "TrafficManager.h"
#include "Ambulance.h"
#include "FireTruck.h"

int main() {
    std::cout << "========================================================\n";
    std::cout << "   EMERGENCY VEHICLE TRAFFIC & ROUTING SYSTEM (C++)    \n";
    std::cout << "========================================================\n";

    TrafficManager manager;

    // 1. createCity()
    manager.createCity();

    // 2. generateTraffic()
    manager.generateTraffic();

    // Load ML Predicted Travel Time Weights from predictions.json (Generated by Python ML)
    std::cout << "\n🤖 Ingesting ML Predicted Weights from predictions.json..." << std::endl;
    manager.loadPredictedWeights("predictions.json");

    // 3. addEmergencyVehicle()
    // Ambulance AMB-911: From Fire Station #1 [Node 2] -> Industrial Park [Node 6]
    auto amb1 = std::make_shared<Ambulance>("AMB-911", 2, 6, true);
    manager.addEmergencyVehicle(amb1);

    // FireTruck ENG-101: From Fire Station #1 [Node 2] -> Central Hospital [Node 1]
    auto fire1 = std::make_shared<FireTruck>("ENG-101", 2, 1, 7500, true);
    manager.addEmergencyVehicle(fire1);

    // 4. calculateRoute()
    // Calculate route for Ambulance AMB-911 using ML predicted graph weights
    RouteResult ambRoute = manager.calculateRoute("AMB-911");

    // Calculate route for Fire Truck ENG-101
    RouteResult fireRoute = manager.calculateRoute("ENG-101");

    // 5. optimizeSignals()
    // Optimize traffic signals along the emergency route for Ambulance AMB-911
    if (ambRoute.found) {
        manager.optimizeSignals(ambRoute.path);
    }

    // Re-evaluate travel time after Green Wave signal optimization
    std::cout << "\n========================================================" << std::endl;
    std::cout << "⏱️  POST-OPTIMIZATION VERIFICATION FOR AMB-911" << std::endl;
    std::cout << "========================================================" << std::endl;
    RouteResult postOptRoute = manager.calculateRoute("AMB-911");
    std::cout << "🎉 Emergency travel time reduced from " << ambRoute.totalTravelTimeMinutes
              << " min to " << postOptRoute.totalTravelTimeMinutes
              << " min after Green Wave signal activation!" << std::endl;

    std::cout << "\n========================================================" << std::endl;
    std::cout << "✅ ALL DEMONSTRATION STEPS COMPLETED SUCCESSFULLY!" << std::endl;
    std::cout << "========================================================\n" << std::endl;

    return 0;
}
