#ifndef TRAFFIC_MANAGER_H
#define TRAFFIC_MANAGER_H

#include <vector>
#include <memory>
#include <map>
#include <iostream>
#include <iomanip>
#include "Graph.h"
#include "Vehicle.h"
#include "Ambulance.h"
#include "FireTruck.h"
#include "Dijkstra.h"

class TrafficManager {
private:
    Graph cityGraph;
    std::vector<std::shared_ptr<Vehicle>> vehicles;
    std::map<std::string, RouteResult> activeRoutes;

public:
    TrafficManager() = default;

    // 1. createCity(): Hardcoded city intersections and roads
    void createCity() {
        std::cout << "\n========================================================" << std::endl;
        std::cout << "🏙️  EXECUTING: createCity()" << std::endl;
        std::cout << "Building Metro City Road Infrastructure & Intersections..." << std::endl;
        std::cout << "========================================================" << std::endl;

        // Intersections
        cityGraph.addIntersection(1, "Central Hospital");
        cityGraph.addIntersection(2, "Fire Station #1");
        cityGraph.addIntersection(3, "Downtown Plaza");
        cityGraph.addIntersection(4, "Residential District");
        cityGraph.addIntersection(5, "Highway Interchange (I-95)");
        cityGraph.addIntersection(6, "Industrial Park");

        // Hardcoded Roads with distance (km), speed limit (km/h), initial signal state
        cityGraph.addRoad(1, 3, 4.5, 50.0, SignalState::GREEN);  // Hospital <-> Downtown
        cityGraph.addRoad(2, 3, 3.0, 50.0, SignalState::RED);    // Fire Station <-> Downtown
        cityGraph.addRoad(2, 4, 5.0, 60.0, SignalState::GREEN);  // Fire Station <-> Residential
        cityGraph.addRoad(3, 4, 2.5, 40.0, SignalState::RED);    // Downtown <-> Residential
        cityGraph.addRoad(3, 5, 6.0, 80.0, SignalState::GREEN);  // Downtown <-> Highway
        cityGraph.addRoad(4, 6, 7.2, 70.0, SignalState::YELLOW); // Residential <-> Industrial
        cityGraph.addRoad(5, 6, 4.0, 90.0, SignalState::GREEN);  // Highway <-> Industrial
        cityGraph.addRoad(1, 5, 5.5, 75.0, SignalState::RED);    // Hospital <-> Highway

        std::cout << "✅ City successfully created with 6 Intersections and 8 Two-Way Roads!" << std::endl;
        cityGraph.displayGraph();
    }

    // Load graph edge weights from predictions.json generated by Python ML model
    bool loadPredictedWeights(const std::string& filepath = "predictions.json") {
        std::cout << "\n========================================================" << std::endl;
        std::cout << "📄  EXECUTING: loadPredictedWeights('" << filepath << "')" << std::endl;
        std::cout << "========================================================" << std::endl;
        return cityGraph.loadPredictedWeights(filepath);
    }

    // 2. generateTraffic(): Simulates dynamic traffic congestion across city roads
    void generateTraffic() {
        std::cout << "\n========================================================" << std::endl;
        std::cout << "🚗  EXECUTING: generateTraffic()" << std::endl;
        std::cout << "Simulating real-time ambient traffic conditions & congestion..." << std::endl;
        std::cout << "========================================================" << std::endl;

        cityGraph.updateRoadCongestion(3, 4, 2.8); // Downtown <-> Residential heavy traffic (2.8x slowdown)
        cityGraph.updateRoadCongestion(1, 3, 1.9); // Hospital <-> Downtown moderate congestion (1.9x slowdown)
        cityGraph.updateRoadCongestion(3, 5, 1.4); // Downtown <-> Highway mild congestion (1.4x slowdown)
        cityGraph.updateRoadCongestion(2, 4, 1.1); // Fire Station <-> Residential clear (1.1x)
        cityGraph.updateRoadCongestion(5, 6, 1.0); // Highway <-> Industrial free flow (1.0x)

        std::cout << "📊 Dynamic Traffic Congestion Multipliers Applied:" << std::endl;
        std::cout << "   • Downtown [3] ↔ Residential [4]    : HEAVY TRAFFIC (2.8x delay)" << std::endl;
        std::cout << "   • Central Hospital [1] ↔ Downtown [3] : MODERATE CONGESTION (1.9x delay)" << std::endl;
        std::cout << "   • Downtown [3] ↔ Highway [5]        : MILD TRAFFIC (1.4x delay)" << std::endl;
        std::cout << "   • Fire Station [2] ↔ Residential [4] : CLEAR TRAFFIC (1.1x delay)" << std::endl;
        std::cout << "   • Highway [5] ↔ Industrial [6]      : FREE FLOW (1.0x delay)" << std::endl;
    }

    // 3. addEmergencyVehicle(): Register an emergency vehicle
    void addEmergencyVehicle(const std::shared_ptr<Vehicle>& vehicle) {
        std::cout << "\n========================================================" << std::endl;
        std::cout << "🚨  EXECUTING: addEmergencyVehicle()" << std::endl;
        std::cout << "Dispatching Emergency Unit to Network..." << std::endl;
        std::cout << "========================================================" << std::endl;

        vehicles.push_back(vehicle);
        vehicle->printInfo();
    }

    void addEmergencyVehicle(const std::string& id, int start, int end, bool isAmbulance = true) {
        if (isAmbulance) {
            addEmergencyVehicle(std::make_shared<Ambulance>(id, start, end, true));
        } else {
            addEmergencyVehicle(std::make_shared<FireTruck>(id, start, end, 6000, true));
        }
    }

    // 5. optimizeSignals(): Overrides traffic signals along emergency route to GREEN ("Green Wave")
    void optimizeSignals(const std::vector<int>& routePath) {
        std::cout << "\n========================================================" << std::endl;
        std::cout << "🚦  EXECUTING: optimizeSignals() - Green Wave Activation" << std::endl;
        std::cout << "========================================================" << std::endl;

        if (routePath.size() < 2) {
            std::cout << "⚠️ Warning: Route path must contain at least 2 intersections." << std::endl;
            return;
        }

        std::cout << "Clearing traffic lights along emergency route corridor..." << std::endl;
        for (size_t i = 0; i < routePath.size() - 1; ++i) {
            int u = routePath[i];
            int v = routePath[i + 1];

            Road* road = cityGraph.getRoad(u, v);
            if (road) {
                road->forceEmergencyGreen();
                std::cout << "   🟢 Corridor [" << u << " ➔ " << v << "] ("
                          << cityGraph.getIntersectionName(v)
                          << ") -> Traffic Signal set to GREEN OVERRIDE 🚨" << std::endl;
            }
        }

        std::cout << "✅ Signals optimized! Green Wave active along emergency corridor." << std::endl;
    }

    void optimizeSignals(const std::string& vehicleId) {
        auto it = activeRoutes.find(vehicleId);
        if (it != activeRoutes.end()) {
            optimizeSignals(it->second.path);
        } else {
            std::cout << "⚠️ Route not pre-calculated for vehicle " << vehicleId << ". Computing route first..." << std::endl;
            RouteResult route = calculateRoute(vehicleId);
            if (route.found) {
                optimizeSignals(route.path);
            }
        }
    }

    // 4. calculateRoute(): Calculates optimal route & AUTO-OPTIMIZES SIGNALS for active emergency vehicle
    RouteResult calculateRoute(const std::string& vehicleId) {
        std::cout << "\n========================================================" << std::endl;
        std::cout << "🧭  EXECUTING: calculateRoute() for Vehicle [" << vehicleId << "]" << std::endl;
        std::cout << "========================================================" << std::endl;

        std::shared_ptr<Vehicle> targetVehicle = nullptr;
        for (const auto& v : vehicles) {
            if (v->getId() == vehicleId) {
                targetVehicle = v;
                break;
            }
        }

        if (!targetVehicle) {
            std::cout << "❌ Vehicle ID '" << vehicleId << "' not found!" << std::endl;
            return RouteResult();
        }

        bool isEmergency = targetVehicle->isEmergency();
        int start = targetVehicle->getStartNode();
        int end = targetVehicle->getEndNode();

        std::cout << "Routing for " << targetVehicle->getType() << " (ID: " << vehicleId
                  << ") from [" << start << "] " << cityGraph.getIntersectionName(start)
                  << " ➔ [" << end << "] " << cityGraph.getIntersectionName(end) << std::endl;

        RouteResult route = Dijkstra::findShortestPath(cityGraph, start, end, isEmergency);

        if (route.found) {
            activeRoutes[vehicleId] = route;

            std::cout << "✨ Optimal Route Calculated via Dijkstra's Algorithm:" << std::endl;
            std::cout << "   Path: ";
            for (size_t i = 0; i < route.path.size(); ++i) {
                std::cout << "[" << route.path[i] << "] " << cityGraph.getIntersectionName(route.path[i]);
                if (i < route.path.size() - 1) std::cout << "  ➡️  ";
            }
            std::cout << std::endl;
            std::cout << "   Total Distance   : " << std::fixed << std::setprecision(2) << route.totalDistanceKm << " km" << std::endl;
            std::cout << "   Pre-Opt Time     : " << std::fixed << std::setprecision(2) << route.totalTravelTimeMinutes << " minutes" << std::endl;

            // AUTO-OPTIMIZE SIGNALS: Automatically activate Green Wave for active emergency vehicle
            if (isEmergency) {
                std::cout << "\n🚨 Emergency Vehicle Active! Automatically optimizing signals along corridor..." << std::endl;
                optimizeSignals(route.path);
                RouteResult optRoute = Dijkstra::findShortestPath(cityGraph, start, end, isEmergency);
                std::cout << "⚡ Auto-Optimized Travel Time: " << std::fixed << std::setprecision(2) << optRoute.totalTravelTimeMinutes << " minutes (Green Wave Active 🟢)" << std::endl;
                activeRoutes[vehicleId] = optRoute;
                return optRoute;
            }
        } else {
            std::cout << "❌ No valid route could be calculated!" << std::endl;
        }

        return route;
    }

    const Graph& getCityGraph() const { return cityGraph; }
};

#endif // TRAFFIC_MANAGER_H
